# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop', models.CharField(max_length=200)),
                ('movie_id', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('popularity', models.FloatField(blank=True)),
                ('poster_path', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
