# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_superfan', '0002_auto_20170504_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
